### Получение суммы зарплат сотрудников
GET http://localhost:8080/employee/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней
GET http://localhost:8080/employee/high-salary\

### Загрузка файла с сотрудниками в БД
POST http://localhost:8080/employees/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="employees"; filename="data.json"
Content-Type: application/json

< ./employees.json
--WebAppBoundary--